{
	"version": 1547796255,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/simplemetal.png",
		"images/dirt.png",
		"images/grass.png",
		"images/platformtexture.png",
		"images/red.png",
		"images/wall.png",
		"images/upblock.png",
		"images/sideblock.png",
		"images/sky.png",
		"images/sun-sheet0.png",
		"images/trippybackground.png",
		"images/factoryoverlay.png",
		"images/cloud-sheet0.png",
		"images/lavatile.png",
		"images/tripplytile-sheet0.png",
		"images/pileobodies-sheet0.png",
		"images/block-sheet0.png",
		"images/walkzone-sheet0.png",
		"images/vertspeedzone-sheet0.png",
		"images/horspeedzone-sheet0.png",
		"images/lava-sheet0.png",
		"images/objective-sheet0.png",
		"images/d1player-sheet0.png",
		"images/d0player-sheet0.png",
		"images/playersprite-sheet0.png",
		"images/playersprite-sheet1.png",
		"images/hoveringsentry-sheet0.png",
		"images/hsentryturret-sheet0.png",
		"images/hoveringsentrysprite-sheet0.png",
		"images/hoveringsentrysprite-sheet1.png",
		"images/warpanim-sheet0.png",
		"images/orbitallaser.png",
		"images/laser-sheet0.png",
		"images/laser-sheet1.png",
		"images/laser-sheet2.png",
		"images/healthbar-sheet0.png",
		"images/bullet-sheet0.png",
		"images/core-sheet0.png",
		"images/shutdownbutton-sheet0.png",
		"images/fadeout-sheet0.png",
		"images/cage-sheet0.png",
		"media/niisekai dungeon nova.m4a",
		"media/niisekai dungeon nova.ogg",
		"media/niisekai ending credits.m4a",
		"media/niisekai ending credits.ogg",
		"media/main theme music.m4a",
		"media/main theme music.ogg",
		"media/even more exciting and intensified.m4a",
		"media/even more exciting and intensified.ogg",
		"media/exciting and intensified.m4a",
		"media/exciting and intensified.ogg",
		"media/heros_day_off.m4a",
		"media/opening theme music.m4a",
		"media/opening theme music.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"redbackground.mp4",
		"ending.mp4",
		"ending2_1.mp4"
	]
}